
    create table blood_request (
        units_requested integer not null check (units_requested>=1),
        id bigint generated by default as identity,
        requested_at timestamp(6),
        reason varchar(1000),
        approved_by varchar(255),
        blood_group varchar(255) not null check (blood_group in ('A_POS','A_NEG','B_POS','B_NEG','AB_POS','AB_NEG','O_POS','O_NEG')),
        hospital_name varchar(255) not null,
        patient_name varchar(255) not null,
        requester_name varchar(255) not null,
        status varchar(255) check (status in ('PENDING','APPROVED','REJECTED')),
        primary key (id)
    );

    create table blood_stock (
        units_available integer not null check (units_available>=0),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        blood_group varchar(255) not null check (blood_group in ('A_POS','A_NEG','B_POS','B_NEG','AB_POS','AB_NEG','O_POS','O_NEG')),
        primary key (id)
    );

    create table donation_appointment (
        units integer not null check (units>=1),
        donor_id bigint not null,
        id bigint generated by default as identity,
        scheduled_at timestamp(6) not null,
        notes varchar(255),
        status varchar(255) check (status in ('SCHEDULED','COMPLETED','CANCELLED')),
        primary key (id)
    );

    create table donor (
        age integer check ((age<=65) and (age>=18)),
        last_donation_date date,
        id bigint generated by default as identity,
        address varchar(500) not null,
        blood_group varchar(255) not null check (blood_group in ('A_POS','A_NEG','B_POS','B_NEG','AB_POS','AB_NEG','O_POS','O_NEG')),
        city varchar(255) not null,
        email varchar(255) not null,
        gender varchar(255) not null,
        name varchar(255) not null,
        phone varchar(255) not null,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        password varchar(255) not null,
        role varchar(255) not null,
        primary key (id)
    );

    alter table if exists donation_appointment 
       add constraint FK283ipwwemr7as7qyyvtv4i17x 
       foreign key (donor_id) 
       references donor;
